
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: DFruit1
      url-base: https://github.com/DFruit1

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: master
      import: app/west.yml
    - name: corne_left
      remote: DFruit1
      revision: master
      path: boards/shields/corne_left
    - name: corne_right
      remote: DFruit1
      revision: master
      path: boards/shields/corne_right

  self:
    path: config

